[package]
name = "darwins_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggegui = "0.3.7"
ggez = "0.9.3"
rand = "0.8.5"
serde = "1.0.192"
serde_json = "1.0.108"
